### ISSUE TITLE
[Bug]: LoadImplementationWithFallback: no implementation loaded successfully after installed windows 11 update

### ISSUE THREAD

**Issue by yshung1971** [dankrusi/WindowsVirtualDesktopHelper#139]
### What happened?

After installed windows 11: 2024-02 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5034765)
Windows restarted then got the error messages as follows:

### WVDH Version

Windows Virtual Desktop Helper Version: 1.15.0.0

### Windows Version

Windows 11 23H2(OS build 22631.3155)

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by Yovvel** [comment]
Got the same error. Not sure if this is helpfull or not, but here is my log output:

`LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22621
Windows Release: 2009
Windows Product: Windows 10 Home
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.14.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10`

I am using W11 22H2 build 22621.3155

**Comment by yshung1971** [comment]
After installed v. 1.16, the problem hav been fixed!! Thanks!
