### ISSUE TITLE
FR: Show initials of destkop name in task bar

### ISSUE THREAD

**Issue by dankrusi** [dankrusi/WindowsVirtualDesktopHelper#30]
Allow an option for an additional icon to show the name of the desktop (first two initials) in the task bar.

Technical: one would have to generate the icons on the fly...

**Comment by dankrusi** [comment]
Enhancement: by default the first two letters are used (or first letter of each word, if multiword), however one can define the desktop name to be "Work Email (WE)", which would then be automatically be parsed to use the initials WE.

**Comment by dankrusi** [comment]
Initial prototype implemented, however the icons in Windows notif area are so small, its impossible to show more than one character. See pink area below:
![image](https://user-images.githubusercontent.com/190233/227492600-a4ff11c2-4419-48d7-b98f-5d3bf791311a.png)
This is the actual drawing area.

Alternate would be to allow for multiple icons, each using one character:
![image](https://user-images.githubusercontent.com/190233/227493020-fb783913-9c1e-4290-b3ab-e97012964349.png)
But the usability is questionable here (one has to manually place the icons in the right order in Windows for this to work).

I suggest only one character is displayed for this feature.

**Comment by tucan555** [comment]
If only one character is possible then it is still useful, but 2 characters are still better.

In the end I think the readability of the icon characters comes down to your own screen size/resolution and taskbar icon size large/small. Also looking at your pink icons above they are barely discernible whereas the white on black are easy to read, so icon background transparency is important.

How about user option for 1 or 2 characters in the icon, and maybe another user option if 2 characters are selected that they could be one above the other instead of side by side?

Thanks
